# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaqna-xeon-backend-server-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaqna-xeon-backend-server-deploy
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: chaqna-xeon-backend-server-deploy
    spec:
      hostIPC: true
      containers:
      - envFrom:
        - configMapRef:
            name: qna-config
        image: 115108445189.dkr.ecr.us-west-1.amazonaws.com/opea:chatqna-megaservice-server
        imagePullPolicy: IfNotPresent
        name: chaqna-xeon-backend-server-deploy
        args:
        ports:
        - containerPort: 8888
      serviceAccountName: default
---
kind: Service
apiVersion: v1
metadata:
  name: chaqna-xeon-backend-server-svc
spec:
  type: NodePort
  selector:
    app: chaqna-xeon-backend-server-deploy
  ports:
    - name: service
      port: 8888
      targetPort: 8888
